dir:
  input: 
  output: 

input_data:
  tiff_suffixes: 
  marker_suffix: 

ground_truth_config:
  dim_resolution: 
  use_marker_radius: False # whether to use the .marker* file radius column or not
  default_max_radius: 3.5
  radius_min: 1.0
  knn_k: 1
  knn_radius_scale: 0.33
  quantize_sigma: 0.1
  downscale_factors: Null

pre_processing_config:
  patch_size: [96, 96, 96]
  positive_patch_prob: 0.8
  pclip: [0.5, 99.5]
